apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect-agent
  namespace: azure-arc
  labels:
    app.kubernetes.io/name:  azure-arc-k8s
    app.kubernetes.io/component: connect-agent
    test: test
  annotations:
    description: {{ .Chart.Description }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azure-arc-k8s
      app.kubernetes.io/component: connect-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azure-arc-k8s
        app.kubernetes.io/component: connect-agent
    spec:
      serviceAccountName: azure-arc-operatorsa
      containers:
        - name: kube-rbac-proxy
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=10"
          ports:
            - containerPort: 8443
              name: https
        - name: connect-agent
          image: "k8connectrpcontainerregistry.azurecr.io/connect:v1"
          imagePullPolicy: Always
          env:
          - name: AZURE_RESOURCE_NAME
            value: "cclogtest"
          - name: AZURE_SUBSCRIPTION_ID
            value: "1bfbb5d0-917e-4346-9026-1d3b344417f5"
          - name: AZURE_RESOURCE_GROUP
            value: "pasankav"
          - name: AZURE_REGION
            value: "eastus"
          - name: AZURE_TENANT_ID
            value: "72f988bf-86f1-41af-91ab-2d7cd011db47"
          - name: AZURE_CLIENT_ID
            value: "03868624-8d8d-45c1-9e8e-5b8af8dd0088"
          - name: AZURE_CLIENT_SECRET
            value: "107d3f90-dc96-4f4d-83ea-bfdc6b4bcaaf"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: connect-agent
  name: connect-agent-service
  namespace: azure-arc
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    app.kubernetes.io/name: azure-arc-k8s
    app.kubernetes.io/component: connect-agent
